apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: javajava-java-sample-n5y6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: javajava-java-sample-n5y6
    app.kubernetes.io/part-of: e2e-java
  name: javajava-java-sample-n5y6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: javajava-java-sample-n5y6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: javajava-java-sample-n5y6
    spec:
      containers:
      - image: quay.io/bootstrap/rhtap-demo-qocd-tenant/e2e-java/javajava-java-sample-n5y6@sha256:7a56f2d00f256382148ec0c4ff399b840bc771db2f7e308e0c542f7db35e518d
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
